apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-test-spring
  namespace: argocd
spec:
  project: arc
  sources:
    - chart: gha-runner-scale-set
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.10.1
      helm:
        valuesObject:
          githubConfigUrl: https://github.com/jamezrin/test-spring
          githubConfigSecret: arc-github-secret
          controllerServiceAccount:
            namespace: arc-systems
            name: arc-controller-gha-rs-controller
        valueFiles:
          - $arc_config/gha-runner-scale-set-dind-fix.yaml
    - repoURL: https://github.com/jamezrin/personal-actions-runner-setup
      targetRevision: main
      ref: arc_config
  destination:
    name: "in-cluster"
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
