apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: postgres-admin-password
      remoteRef:
        key: "8e60f660-546c-409a-b007-b25701199a15"
    - secretKey: postgres-user-password
      remoteRef:
        key: "ddfce7fe-27a9-4bb8-bff6-b2570120ac47"
    - secretKey: postgres-replication-password
      remoteRef:
        key: "934c67c8-d53e-4b09-adc5-b2570120bc05"
