apiVersion: v1
kind: Service
metadata:
  labels:
    app: loaderio-nginx-proxy
  name: loaderio-nginx-proxy
  namespace: apps
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: loaderio-nginx-proxy
  sessionAffinity: None
  type: ClusterIP
