apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "8e60f660-546c-409a-b007-b25701199a15"
    - secretKey: password
      remoteRef:
        key: "ddfce7fe-27a9-4bb8-bff6-b2570120ac47"
