apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: timeit-backend
  name: timeit-backend
  namespace: apps
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: timeit-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: timeit-backend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "80"
            - name: TIMEIT_EMAIL_HOST
              value: email-smtp.eu-west-3.amazonaws.com
            - name: TIMEIT_EMAIL_PORT
              value: "465"
            - name: TIMEIT_EMAIL_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: timeit-aws-ses-smtp
            - name: TIMEIT_EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: timeit-aws-ses-smtp
            - name: TIMEIT_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: timeit-jwt-secret
            - name: TIMEIT_EMAIL_FROM_LINE
              value: "\"Jaime de TimeIt\" <no-reply@jamezrin.com>"
            - name: TIMEIT_CRYPT_ROUNDS
              value: "10"
            - name: TIMEIT_CORS_ORIGINS
              value: https://timeit.jamezrin.com
            - name: TIMEIT_FRONTEND_URL
              value: https://timeit.jamezrin.com
            - name: TIMEIT_COOKIE_DOMAIN
              value: timeit.jamezrin.com
            - name: TIMEIT_COOKIE_SECURE
              value: "true"
            - name: TIMEIT_RUN_MIGRATIONS
              value: "true"
            - name: TYPEORM_CONNECTION
              value: postgres
            - name: TYPEORM_HOST
              value: postgresql-primary.postgresql
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-apps-secret
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-apps-secret
            - name: TYPEORM_DATABASE
              value: timeit_prd
            - name: TYPEORM_PORT
              value: "5432"
            - name: TYPEORM_SYNCHRONIZE
              value: "false"
            - name: TYPEORM_LOGGING
              value: "false"
          image: harbor.jamezrin.com/library/timeit-backend
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          name: timeit-backend
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: harbor-apps-dockerconfig
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
