apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timeit-jwt-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: secret
      remoteRef:
        key: "4193aac7-7512-4667-ba0d-b25800cee0ac"
