apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    name: ''
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  sources:
    - repoURL: 'https://traefik.github.io/charts'
      targetRevision: 28.3.0
      chart: traefik
      helm:
        valueFiles:
          - $values/traefik/values.yaml
    - repoURL: 'https://github.com/jamezrin/personal-cluster-argocd'
      path: traefik
      ref: values
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
