apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch-secret
  namespace: elasticsearch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: elasticsearch-password
      remoteRef:
        key: "1fd57067-d070-4520-97a2-b258010cfb3c"
