apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rpp-public
  name: rpp-public
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rpp-public
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rpp-public
    spec:
      containers:
        - env:
            - name: RPP_DISCORD_USERNAME
              value: "Rustsense ᴘʀᴏ"
            - name: RPP_DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: rpp-public
            - name: RPP_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: rpp-public
            - name: RPP_DISCORD_OWNER_USER_ID
              value: "130442930686132224"
          image: ghcr.io/rust-sense/bot:latest
          imagePullPolicy: Always
          name: rustplusplus
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/credentials
              name: data
              subPath: credentials
            - mountPath: /app/instances
              name: data
              subPath: instances
            - mountPath: /app/logs
              name: data
              subPath: logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ghcr-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rpp-public-data
