apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rpp-public-external
spec:
  refreshInterval: 0.03m
  target:
    name: rpp-public
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-secret-store
  data:
    - secretKey: client-id
      remoteRef:
        key: rpp-public-discord-client-id
    - secretKey: token
      remoteRef:
        key: rpp-public-discord-token
