apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rpp-public-external
spec:
  refreshInterval: 0.03m
  target:
    name: rpp-public
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-store
  data:
    - secretKey: client-id
      remoteRef:
        key: 5c5038d0-66f7-4855-a5da-b258001fc396
    - secretKey: token
      remoteRef:
        key: 48d50ad7-9a00-476a-a532-b258001fe43e
