apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-registry-external-secret
spec:
  refreshInterval: 1h
  target:
    name: ghcr-registry-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .value | toString }}"
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-secret-store
  data:
  - secretKey: value
    remoteRef:
      key: ghcr-registry-dockerconfigjson
