apiVersion: v1
kind: ConfigMap
metadata:
  name: loaderio-nginx-config
  namespace: apps
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html index.htm;

      location ~ ^/loaderio-3fab2f0ee151780b66d429736d2878de {
        return 200 'loaderio-3fab2f0ee151780b66d429736d2878de';
        add_header Content-Type text/plain;
      }
    }
