apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rpp-private
  name: rpp-private
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rpp-private
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rpp-private
    spec:
      containers:
        - env:
            - name: RPP_DISCORD_USERNAME
              value: Jamezbot Private
            - name: RPP_DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: rpp-private-secret
            - name: RPP_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: rpp-private-secret
          image: ghcr.io/rust-companion/bot:unstable
          imagePullPolicy: Always
          name: rustplusplus
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/credentials
              name: data
              subPath: credentials
            - mountPath: /app/instances
              name: data
              subPath: instances
            - mountPath: /app/logs
              name: data
              subPath: logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: personal-registry
        - name: ghcr-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rpp-private-data
