apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rpp-private-external
spec:
  refreshInterval: 0.03m
  target:
    name: rpp-private
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-store
  data:
    - secretKey: client-id
      remoteRef:
        key: 627472eb-950c-419e-a0d3-b258002019a4
    - secretKey: token
      remoteRef:
        key: 28a5b099-3ea8-4ac7-9485-b25800203432
