apiVersion: v1
kind: PersistentVolumeClaim
spec:
  metadata:
    name: rpp-private-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
