apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: argocd
spec:
  project: dataeng
  sources:
    - chart: airbyte
      repoURL: https://airbytehq.github.io/helm-charts
      targetRevision: 1.5.0
      helm:
        valuesObject:
          global:
            airbyteUrl: https://airbyte.jamezrin.com

            auth:
              enabled: true
              firstName: "Jaime"
              lastName: "Martínez Rincón"
          webapp:
            ingress:
              enabled: true
              className: traefik
              hosts:
                - host: airbyte.jamezrin.com
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: airbyte-tls
                  hosts:
                    - airbyte.jamezrin.com
  destination:
    name: "in-cluster"
    namespace: airbyte
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
