apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: databases
  sources:
    - chart: mongodb
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 16.4.3
      helm:
        valuesObject:
          architecture: replicaset
          replicaCount: 2
          externalAccess:
            enabled: true
            service:
              type: LoadBalancer
              loadBalancerClass: tailscale
            autoDiscovery:
              enabled: true
          serviceAccount:
            create: true
          automountServiceAccountToken: true
          rbac:
            create: true
          auth:
            # existingSecret: mongodb-secret
            rootPassword: randomvalue1
            replicaSetKey: randomvalue2
            usernames:
              - username1
              - username2
            passwords:
              - password1
              - password2
            databases:
              - database1
              - database2
    - repoURL: "https://github.com/jamezrin/personal-cluster-argocd"
      path: mongodb
      targetRevision: main
      directory:
        recurse: true
  destination:
    name: "in-cluster"
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
