apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: "https://github.com/jamezrin/personal-cluster-argocd"
    path: playground
    targetRevision: main
  destination:
    name: "in-cluster"
    namespace: playground
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      