apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: databases
  sources:
    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 16.3.4
      helm:
        valuesObject:
          primary:
            service:
              annotations:
                tailscale.com/expose: "true"
          readReplicas:
            service:
              annotations:
                tailscale.com/expose: "true"
    - repoURL: "https://github.com/jamezrin/personal-cluster-argocd"
      path: postgresql
      targetRevision: main
      directory:
        recurse: true
  destination:
    name: "in-cluster"
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
