apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: databases
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.6.1
    helm:
      valuesObject:
        master:
          service:
            annotations:
              tailscale.com/expose: "true"
        replica:
          service:
            annotations:
              tailscale.com/expose: "true"
        sentinel:
          enabled: true
          service:
            annotations:
              tailscale.com/expose: "true"
  destination:
    name: "in-cluster"
    namespace: redis
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
