apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solr
  namespace: argocd
spec:
  project: databases
  sources:
    - chart: solr
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 9.5.3
      helm:
        valuesObject:
          auth:
            existingSecret: solr-secret
            existingSecretPasswordKey: solr-password
          service:
            annotations:
              tailscale.com/expose: "true"
    - repoURL: "https://github.com/jamezrin/personal-cluster-argocd"
      path: solr
      targetRevision: main
      directory:
        recurse: true
  destination:
    name: "in-cluster"
    namespace: solr
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
