apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solr
  namespace: argocd
spec:
  project: databases
  source:
    chart: solr
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 9.5.0
    helm:
      valuesObject:
        service:
          annotations:
            tailscale.com/expose: "true"
  destination:
    name: "in-cluster"
    namespace: solr
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
