apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/jamezrin/personal-cluster-argocd"
    path: whoami
    targetRevision: main
  destination:
    name: "in-cluster"
    namespace: whoami
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
