apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-apps-dockerconfig
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: harbor-apps-dockerconfig
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"http://harbor.jamezrin.com":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: "4e9eeb26-06e7-4bfa-9339-b258002a2309"
    - secretKey: password
      remoteRef:
        key: "8bf7e7ba-9987-4779-a914-b258002a4519"
