apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-apps-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "1e27084b-06a3-4a6c-b6a8-b25800244f47"
    - secretKey: password
      remoteRef:
        key: "df1e435c-8400-4638-9ce5-b25800247309"
