apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: solr-secret
  namespace: solr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: solr-password
      remoteRef:
        key: "c9c3725d-7e7c-4a5d-87b3-b27800ec780e"
