apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scylladb-secret
  namespace: scylladb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: scylladb-password
      remoteRef:
        key: "9966db68-39ff-4d50-ba1b-b25801012184"
