apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-github-secret-external
  namespace: arc-runners
spec:
  refreshInterval: 0.03m
  target:
    name: arc-github-secret
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-store
  data:
    - secretKey: github_token
      remoteRef:
        key: 214ddc62-8457-4dc6-910f-b258001ceca1
