apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-github-secret-external
spec:
  refreshInterval: 0.03m
  target:
    name: arc-github-secret
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-secret-store
  data:
    - secretKey: github_token
      remoteRef:
        key: arc-github-pat-token

