apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-rust-sense
  namespace: argocd
spec:
  project: default
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
  destination:
    name: "in-cluster"
    namespace: arc-runners

