apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: playground-external-secret
spec:
  refreshInterval: 0.03m
  target:
    name: playground-secrets
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-secret-store
  data:
    - secretKey: key
      remoteRef:
        key: playground-secret-key
