apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-aylamusica-state
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: local-path
