apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: aylamusica-http
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`aylamusica.jamezrin.com`)
      middlewares:
        - name: https-redirectscheme
          namespace: apps
      services:
        - kind: Service
          name: aylamusica
          port: 3000
