apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-aylamusica-storage
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
