apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aylamusica-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: secret_key_base
      remoteRef:
        key: "85a32bcc-b1e8-4f45-8207-b25800e05c7b"
