apiVersion: v1
kind: Service
metadata:
  labels:
    app: aylamusica
  name: aylamusica
  namespace: apps
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: aylamusica
  sessionAffinity: None
  type: ClusterIP
